import React, { useRef, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Horizontal Scroller with CSS</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>

        
//       </main>
//     </>
//   )
// }

const Home = () => {

  const sectionRef = useRef(null)
  const triggerRef = useRef(null)
  const overRef = useRef(null)
  const over = overRef.current

  gsap.registerPlugin(ScrollTrigger)
  const tl = gsap.timeline()

  useEffect(() => {

    const pins = gsap.fromTo(sectionRef.current, {
      translateX: 0
    }, {
      translateX: "-300vw",
      ease: "none",
      duration: 1,
      scrollTrigger: {
        trigger: triggerRef.current,
        start: "top top",
        end: "2000 top",
        scrub: true,
        pin: true
      }
    })

    return () => {
      pins.kill()
    }

  }, [])

  const bg = []

  return (
    <>
      <div ref={triggerRef} className={styles.outer}>
        <div ref={sectionRef} className={styles.scrollContainer}>
          <div className={styles.scroller}>
            <h3 className={styles.scrollerText}>SECTION 1</h3>
          </div>
          <div className={styles.scroller}>
            <h3 className={styles.scrollerText}>SECTION 2</h3>
          </div>
          <div className={styles.scroller}>
            <h3 className={styles.scrollerText}>SECTION 3</h3>
          </div>
          <div className={styles.scroller}>
            <h3 className={styles.scrollerText}>SECTION 4</h3>
          </div>
        </div>
      </div>

      <div className={styles.footer}>
        <h3 className={styles.scrollerText}>Footer</h3>
      </div>

      {/* <section className={styles.container}>
        <div data-scroll-section className={styles.containerChild}>
          <div className={styles.background}></div>
          <div className={styles.letter}>F</div>
        </div>

        <div className={styles.containerChild}>
          <div className={styles.background}></div>
          <div className={styles.letter}>O</div>
        </div>
        <div className={styles.containerChild}>
          <div className={styles.background}></div>
          <div className={styles.letter}>R</div>
        </div>
      </section> */}
    </>
  )
}

export default Home
